name: Swift Package Manager

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: swift test

